# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

books = [{:title => "Nudge: Improving Decisions About Health, Wealth, and Happiness", :publish_date => "April 8th 2008", :genre => "Philosophy", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1328828013l/2527900.jpg", :summary => "Every day, we make decisions on topics ranging from personal investments to schools for our children to the meals we eat to the causes we champion. Unfortunately, we often choose poorly. The reason, the authors explain, is that, being human, we all are susceptible to various biases that can lead us to blunder. Our mistakes make us poorer and less healthy; we often make bad decisions involving education, personal finance, health care, mortgages and credit cards, the family, and even the planet itself.Thaler and Sunstein invite us to enter an alternative world, one that takes our humanness as a given. They show that by knowing how people think, we can design choice environments that make it easier for people to choose what is best for themselves, their families, and their society. Using colorful examples from the most important aspects of life, Thaler and Sunstein demonstrate how thoughtful �choice architecture” can be established to nudge us in beneficial directions without restricting freedom of choice. Nudge offers a unique new take—from neither the left nor the right—on many hot-button issues, for individuals and governments alike. This is one of the most engaging and provocative books to come along in many years."},
              {:title => "Rot and Ruin", :publish_date => "September 14th 2010", :genre => "Horror", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1264898635l/7157310.jpg", :summary => "In the zombie-infested, post-apocalyptic America where Benny Imura lives, every teenager must find a job by the time they turn fifteen or get their rations cut in half. Benny doesn't want to apprentice as a zombie hunter with his boring older brother Tom, but he has no choice. He expects a tedious job whacking zoms for cash, but what he gets is a vocation that will teach him what it means to be human."},
              {:title => "Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened", :publish_date => "October 29th 2013", :genre => "Humor", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1376509449l/17571007.jpg", :summary => "Every time Allie Brosh posts something new on her hugely popular blog Hyperbole and a Half the internet rejoices.Touching, absurd, and darkly comic, Allie Brosh's highly anticipated book Hyperbole and a Half showcases her unique voice, leaping wit, and her ability to capture complex emotions with deceptively simple illustrations.This full-color, beautifully illustrated edition features more than fifty percent new content, with ten never-before-seen essays and one wholly revised and expanded piece as well as classics from the website like 'The God of Cake' 'Dogs Don't Understand Basic Concepts Like Moving' and her astonishing 'Adventures in Depression' and 'Depression Part Two' which have been hailed as some of the most insightful meditations on the disease ever written.The debut of Brosh marks the launch of a major new American humorist who will surely make even the biggest scrooge or snob laugh. We dare you not to."},
              {:title => "The Outsiders", :publish_date => "November 1st 1997", :genre => "Young Adult Fiction", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1314327508l/231804.jpg", :summary => "According to Ponyboy, there are two kinds of people in the world: greasers and socs. A soc (short for 'social') has money, can get away with just about anything, and has an attitude longer than a limousine. A greaser, on the other hand, always lives on the outside and needs to watch his back. Ponyboy is a greaser, and he's always been proud of it, even willing to rumble against a gang of socs for the sake of his fellow greasers--until one terrible night when his friend Johnny kills a soc. The murder gets under Ponyboy's skin, causing his bifurcated world to crumble and teaching him that pain feels the same whether a soc or a greaser."},
              {:title => "The Fellowship of the Ring", :publish_date => "September 5th 2003", :genre => "Fantasy", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1298411339l/34.jpg", :summary => "Frodo Baggins knew the Ringwraiths were searching for him - and the Ring of Power he bore that would enable Sauron to destroy all that was good in Middle-earth. Now it was up to Frodo and his faithful servant Sam to carry the Ring to where it could be detroyed - in the very center of Sauron's dark kingdom."},
              {:title => "The Godfather", :publish_date => "March 1st 2002", :genre => "Crime", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1195309998l/22034.jpg", :summary => "More than thirty years ago, a classic was born. A searing novel of the Mafia underworld, The Godfather introduced readers to the first family of American crime fiction, the Corleones, and the powerful legacy of tradition, blood, and honor that was passed on from father to son. With its themes of the seduction of power, the pitfalls of greed, and family allegiance, it resonated with millions of readers across the world—and became the definitive novel of the virile, violent subculture that remains steeped in intrigue, in controversy, and in our collective consciousness."},
              {:title => "Harry Potter and the Deathly Hallows", :publish_date => "August 1st 2007", :genre => "Fantasy", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1370023538l/136251.jpg", :summary => "'His hand closed automatically around the fake Horcrux, but in spite of everything, in spite of the dark and twisting path he saw stretching ahead for himself, in spite of the final meeting with Voldemort he knew must come, whether in a month, in a year, or in ten, he felt his heart lift at the thought that there was still one last golden day of peace left to enjoy with Ron and Hermione.' With these words 'Harry Potter and the Half-Blood Prince' draws to a close. And here, in this seventh and final book, Harry discovers what fate truly has in store for him as he inexorably makes his way to that final meeting with Voldemort. In this thrilling climax to the phenomenally bestselling series, J.K. Rowling will reveal all to her eagerly waiting readers"},
              {:title => "Star Trek", :publish_date => "May 12th 2009", :genre => "Science Fiction", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1348936238l/6344943.jpg", :summary => "The origins of James Kirk, Spock and the crew of the USS Enterprise from the 2009 film 'Star Trek' and how these iconic characters came together in the alternate reality caused by Nero's time travel. This book is the novelization of the 2009 film of the same name."},
              {:title => "Star Wars: A Long Time Ago..., Book 2: Dark Encounters", :publish_date => "August 5th 2002", :genre => "Science Fiction", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1348753583l/78722.jpg", :summary => "A long time ago, in a decade that was far, far out there, moviedom's most beloved characters made the transition from silver screen to printed page in a comic-book series that was truly out of this world. Each new issue of Marvel's Star Wars comic-book series that launched in 1977 was stranger and crazier than the next. Where else could you find the friendship between Luke Skywalker and C-3PO turning the heart of Valance, a ruthless, cyborg bounty hunter? Or a team of vengeful imperial brothers, led by Baron Orman Tagge, who seek to bring the frozen fury of their Omega Frost to Tatooine and the Rebel Alliance fleet? Or an early version of Jabba the Hutt as a humanoid seal instead of a drooling space slug? Now, for the first time ever, the entire Marvel Star Wars comic-book series is collected in book format, bringing these hard-to-find gems from dusty collectors' boxes to your home library. Whether you're a tried-and-true Star Wars fan, a lover of pop culture, or a collector of kitsch, each stand-alone book in this seven-volume collection will amaze, amuse, and delight."},
              {:title => "Memoirs of a Geisha", :publish_date => "November 15th 2005", :genre => "Historical Fiction", :image_url => "http://d202m5krfqbpi5.cloudfront.net/books/1388367666l/930.jpg", :summary => "In this literary tour de force, novelist Arthur Golden enters a remote and shimmeringly exotic world. For the protagonist of this peerlessly observant first novel is Sayuri, one of Japan's most celebrated geisha, a woman who is both performer and courtesan, slave and goddess.We follow Sayuri from her childhood in an impoverished fishing village, where in 1929, she is sold to a representative of a geisha house, who is drawn by the child's unusual blue-grey eyes. From there she is taken to Gion, the pleasure district of Kyoto. She is nine years old. In the years that follow, as she works to pay back the price of her purchase, Sayuri will be schooled in music and dance, learn to apply the geisha's elaborate makeup, wear elaborate kimono, and care for a coiffure so fragile that it requires a special pillow. She will also acquire a magnanimous tutor and a venomous rival. Surviving the intrigues of her trade and the upheavals of war, the resourceful Sayuri is a romantic heroine on the order of Jane Eyre and Scarlett O'Hara. And Memoirs of a Geisha is a triumphant work - suspenseful, and utterly persuasive."}]

